### ISSUE TITLE
Add auth command

### ISSUE THREAD

**Issue by pogosheep** [super3/IRC-Bot#12]
The bot is currently not able to auth at a server.

Add the configuration and the command, so the bot is able to do.
Check after connecting if the configuration is available and execute the command without calling from extern.

Perhaps it's a good idea to define the command as 'private'. No one will be able to call the command like '!auth'.

**Comment by Yoshi2889** [comment]
I implemented hostname verification in my copy of the bot, and added a $verify flag to every command. When a command is about to get run, the bot verifies the hostname, and refuses to run if it doesn't match.

This way, it relies on NickServ authentication, because a cloak is only applied to a user once he/she is logged in.

For this, add this block of code to Classes/Library/IRC/Command/Base.php, function executeCommand, right after the $this->data = $data; line:
```
            // Do we verify the legitimacy of the user executing?
            if (!empty($this->verify))
            {
		// Get the host.
		preg_match("/~([^\s]++)++/", $this->data, $hosts);
		
		// Check if the user has privileges.
		$this->bot->log('Requesting privileges for host ' . $hosts[0] . '...');
		if (!in_array($hosts[0], $config['hosts']))
		{
			// Nope. No access for you.
			$this->bot->log('Failed; this host is not trusted.');
			$this->say('You are not privileged to run this command.');
			return;
		}
		
		$this->bot->log('Success; proceeding with command.');
            }
```
And add "global $config;" at the very top of the function.

In your config.local.php file, add the following:
```
	'hosts' => array(
		'Your host here...',
	),
```

This solution works flawlessly for me.

**Comment by TimTims** [comment]
Yoshi if you make a pull request I'll add that function in there. It's very handy to have. Thank you by the way.
